name: Android Build

on:
  push:
    branches:
      - 'dev'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:  # ✅ Make sure "steps" is present
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          sudo mkdir -p /usr/local/lib/android/sdk/cmdline-tools
          cd /usr/local/lib/android/sdk/cmdline-tools
          sudo wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo unzip cmdline-tools.zip -d .
          sudo mv cmdline-tools latest
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew app:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ github.workspace }}/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        id: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}