name: Android Build

on:
  push:
    branches:
      - 'dev'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:  # ✅ Make sure "steps" is present
      - name: Check out Git repository
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '17'

      - name: Install Android SDK Build Tools
        run: |
          sudo mkdir -p /usr/local/lib/android/sdk
          sudo chmod -R 777 /usr/local/lib/android/sdk
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3"
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew app:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ github.workspace }}/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        id: uploadArtifact
        uses: awalsh128/cache-apt-pkgs-action@v1.4.3
        with:
          name: app
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}