name: Android Build

on:
  push:
    branches:
      - 'dev'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew app:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ github.workspace }}/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        id: uploadArtifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}

  deploy-apk:
    name: Deploy APK to GitHub Releases
    runs-on: ubuntu-latest
    needs: android-build
    steps:
      - name: Download APK Artifact
        uses: actions/download-artifact@v3
        with:
          name: app
          path: .

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: app-release.apk
          tag_name: v1.0.${{ github.run_number }}
          body: "New Android release build"
          draft: false
          prerelease: false

 