name: Android Build

on:
  push:
    branches:
      - 'dev'

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest
    steps:  # ✅ Make sure "steps" is present
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android Release
        run: |
          cd android && ./gradlew clean && ./gradlew app:assembleRelease

      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: ${{ github.workspace }}/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        id: uploadArtifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ${{ steps.sign_app.outputs.signedReleaseFile }}