name: iOS Build

on:
  push:
    branches:
      - dev  # Trigger on push to the main branch

jobs:
  ios-build:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable


      - name: Install dependencies
        run: yarn install --frozen-lockfile --network-timeout 300000

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update

# Step 1: Build iOS app
      - name: Build iOS app
        run: |
          cd ios && pod install
          xcodebuild -workspace ios/ci_test.xcworkspace \
            -scheme ci_test \
            -configuration Release \
            -sdk iphoneos

# Step 2: Archive iOS app (create .xcarchive file)
      - name: Archive iOS app
        run: |
          xcodebuild -workspace ios/ci_test.xcworkspace \
            -scheme ci_test \
            -configuration Release \
            -sdk iphoneos \
            -archivePath ${{ github.workspace }}/ios/build/ci_test.xcarchive archive

      # Step 3: Export IPA
      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/ios/build/ci_test.xcarchive \
            -exportPath ${{ github.workspace }}/ios/build/ \
            -exportOptionsPlist ${{ github.workspace }}/ios/ExportOptions.plist
                  
      - name: Upload IPA to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_IOS }}
          token: ${{ secrets.FIREBASE_AUTH_TOKEN }}
          file: ios/build/ci_test.ipa
          groups: "ios"